import {readFile,writeFile,mkdir} from 'node:fs/promises';import {dirname} from 'node:path';import {base,rootFor,canonical} from '../src/templates/base.mjs';import pageTemplate from '../src/templates/page.mjs';import noticiaTemplate from '../src/templates/noticia.mjs';import {personagemTemplate,veiculoTemplate,armaTemplate,missaoTemplate,localTemplate,guiaTemplate} from '../src/templates/entity.mjs';import {intro,image,badge} from '../src/templates/common.mjs';
const read=async p=>JSON.parse(await readFile(p,'utf8'));const write=async(p,s)=>{await mkdir(dirname(p),{recursive:true});await writeFile(p,s)};
const pages=await read('src/data/pages.json'),catalogs=await read('src/data/catalogs.json');const data={};for(const x of ['noticias','personagens','veiculos','armas','missoes','locais','guias'])data[x]=await read(`src/data/${x}.json`);
const generated=[];const add=async p=>{await write(p.slug?`${p.slug}/index.html`:'index.html',base(p));generated.push(p)};
const card=(e,type,root)=>`<article class="card" data-filter-group="catalog" data-filter-item="${(e.categoria||'todos').toLowerCase()}">${image(e,root,type)}<div class="card-body">${badge(e.status)}<h2>${e.nome||e.titulo}</h2><p class="muted">${e.resumo}</p><a class="btn btn-secondary" href="${root}${type}/${e.slug}/">Ver conteúdo</a></div></article>`;
const catalogPage=(type,items)=>{const c=catalogs[type],root=rootFor(type);return {slug:type,title:c.title,description:c.description,body:`${intro({title:c.title,description:c.description},root)}<section class="section"><div class="container"><div class="filter-row" data-filter-group="catalog"><button class="filter active" data-filter="all">Todas</button>${c.filters.map(x=>`<button class="filter" data-filter="${x.toLowerCase()}">${x}</button>`).join('')}</div><div class="grid grid-3">${items.length?items.map(e=>card(e,type,root)).join(''):'<div class="empty-state"><strong>Conteúdo em preparação</strong><p>CONTEÚDO DEMONSTRATIVO — nenhuma informação fictícia é apresentada como real.</p></div>'}</div></div></section>`}};
for(const p of pages)await add(pageTemplate(p,rootFor(p.slug)));
for(const type of Object.keys(catalogs))await add(catalogPage(type,data[type]||[]));
const newsRoot=rootFor('noticias'),newsFilters=['Todas','GTA 6','Rockstar','Trailers','Gameplay','Mapa','Personagens','Veículos','Online','Atualizações','Rumores'];await add({slug:'noticias',title:'Notícias',description:'Cobertura editorial organizada, com separação clara entre confirmação, rumor e teoria.',body:`${intro({title:'Notícias',description:'Cobertura editorial organizada, com separação clara entre confirmação, rumor e teoria.'},newsRoot)}<section class="section"><div class="container"><div class="filter-row" data-filter-group="news">${newsFilters.map((x,i)=>`<button class="filter${i?'':' active'}" data-filter="${i?x.toLowerCase():'all'}">${x}</button>`).join('')}</div><div class="grid grid-3">${data.noticias.map(e=>`<article class="card" data-filter-group="news" data-filter-item="${e.categoria.toLowerCase()}">${image(e,newsRoot,'noticias')}<div class="card-body">${badge(e.status)}<p class="meta">${e.categoria} · ${e.data||'Data a definir'}</p><h2>${e.titulo}</h2><h3>${e.subtitulo}</h3><p>${e.resumo}</p><a class="btn btn-secondary" href="${newsRoot}noticias/${e.slug}/">Ler notícia</a></div></article>`).join('')}</div></div></section>`});
for(const e of data.noticias)await add(noticiaTemplate(e,rootFor(`noticias/${e.slug}`)));for(const e of data.personagens)await add(personagemTemplate(e,rootFor(`personagens/${e.slug}`)));for(const e of data.veiculos)await add(veiculoTemplate(e,rootFor(`veiculos/${e.slug}`)));for(const e of data.armas)await add(armaTemplate(e,rootFor(`armas/${e.slug}`)));for(const e of data.missoes)await add(missaoTemplate(e,rootFor(`missoes/${e.slug}`)));for(const e of data.locais)await add(localTemplate(e,rootFor(`locais/${e.slug}`)));for(const e of data.guias.filter(x=>!x.paginaExistente))await add(guiaTemplate(e,rootFor(`guias/${e.slug}`)));
const notFound={slug:'404',is404:true,indexar:false,title:'Página não encontrada',description:'Essa área de Leonida ainda não foi encontrada.',body:`<section class="page-intro"><div class="container"><nav class="breadcrumb" aria-label="Breadcrumb"><a href="/">Início</a> › Página não encontrada</nav><span class="eyebrow">GTA6ZOONE</span><h1>Página não encontrada</h1><p class="lede">Essa área de Leonida ainda não foi encontrada. Verifique o endereço ou escolha um caminho abaixo.</p></div></section><section class="section"><div class="container"><div class="empty-state"><h2>Erro 404</h2><p>A página solicitada não existe.</p><div style="display:flex;gap:.5rem;justify-content:center;flex-wrap:wrap"><a class="btn" href="/">Voltar ao início</a><a class="btn btn-secondary" href="/wiki/">Explorar a Wiki</a><a class="btn btn-secondary" href="/mapa/">Abrir o mapa</a></div></div></div></section>`};await write('404.html',base(notFound));
const urls=generated.filter(x=>x.indexar!==false).map(x=>canonical(x.slug)).sort((a,b)=>a.localeCompare(b,'pt-BR'));await write('sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.map(x=>`  <url><loc>${x}</loc></url>`).join('\n')}\n</urlset>\n`);
const searchMap={noticias:'notícias',personagens:'personagens',veiculos:'veículos',armas:'armas',missoes:'missões',locais:'locais',guias:'guias'};for(const [type,items] of Object.entries(data)){await write(`assets/data/${type}.json`,JSON.stringify(items.map(e=>({titulo:e.titulo||e.nome,resumo:e.resumo,tipo:searchMap[type],url:`${type}/${e.slug}/`})),null,2)+'\n')}
console.log(`Build concluído: ${generated.length+1} HTML, sitemap e índices de busca.`);
